aropixel_admin_page_category:
  resource: |
    alias: aropixel.page_category
    section: admin
    path: pages/categories
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: aropixel_admin_page_category
    vars:
        all:
            subheader: aropixel.ui.category
        index:
            icon: 'tags'
  type: sylius.resource

aropixel_admin_page:
  resource: |
    alias: aropixel.page
    section: admin
    path: pages
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: aropixel_admin_page
    vars:
        all:
            subheader: aropixel.ui.page
            templates:
                form: "@AropixelSyliusPagesPlugin/Admin/Form/Crud/_form.html.twig"
        index:
            icon: 'file alternate'
        update:
  type: sylius.resource

aropixel_page_plugin_show_page:
  controller: aropixel_sylius_pages_plugin.controller.page:showPage
  path: /page/{categorySlug}/{pageSlug}
  methods: GET
